// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "encoding/json"
import "fmt"
import "reflect"

type AccountListAccountList int

var enumValues_AccountListAccountList = []interface{}{
	1,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AccountListAccountList) UnmarshalJSON(b []byte) error {
	var v int
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_AccountListAccountList {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_AccountListAccountList, v)
	}
	*j = AccountListAccountList(v)
	return nil
}

// Returns all accounts belonging to the authorized user.
type AccountList struct {
	// Must be `1`
	AccountList AccountListAccountList `json:"account_list"`

	// [Optional] Used to pass data through the websocket, which may be retrieved via
	// the `echo_req` output field.
	Passthrough AccountListPassthrough `json:"passthrough,omitempty"`

	// [Optional] Used to map request to response.
	ReqId *int `json:"req_id,omitempty"`
}

// [Optional] Used to pass data through the websocket, which may be retrieved via
// the `echo_req` output field.
type AccountListPassthrough map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AccountList) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["account_list"]; !ok || v == nil {
		return fmt.Errorf("field account_list in AccountList: required")
	}
	type Plain AccountList
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = AccountList(plain)
	return nil
}
