// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "encoding/json"
import "fmt"
import "reflect"

// A message with results is received
type CopyStopResp struct {
	// Copy stopping confirmation. Returns 1 is success.
	CopyStop *int `json:"copy_stop,omitempty"`

	// Echo of the request made.
	EchoReq CopyStopRespEchoReq `json:"echo_req"`

	// Action name of the request made.
	MsgType CopyStopRespMsgType `json:"msg_type"`

	// Optional field sent in request to map to response, present only when request
	// contains `req_id`.
	ReqId *int `json:"req_id,omitempty"`
}

// Echo of the request made.
type CopyStopRespEchoReq map[string]interface{}

type CopyStopRespMsgType string

const CopyStopRespMsgTypeCopyStop CopyStopRespMsgType = "copy_stop"

var enumValues_CopyStopRespMsgType = []interface{}{
	"copy_stop",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CopyStopRespMsgType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CopyStopRespMsgType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_CopyStopRespMsgType, v)
	}
	*j = CopyStopRespMsgType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CopyStopResp) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["echo_req"]; raw != nil && !ok {
		return fmt.Errorf("field echo_req in CopyStopResp: required")
	}
	if _, ok := raw["msg_type"]; raw != nil && !ok {
		return fmt.Errorf("field msg_type in CopyStopResp: required")
	}
	type Plain CopyStopResp
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = CopyStopResp(plain)
	return nil
}
