// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "fmt"
import "encoding/json"
import "reflect"

// Statistics of the trader
type CopytradingStatisticsRespCopytradingStatistics struct {
	// This is the epoch the investor started trading.
	ActiveSince int `json:"active_since"`

	// Average seconds of keeping positions open.
	AvgDuration int `json:"avg_duration"`

	// Average loss of trades in percentage.
	AvgLoss float64 `json:"avg_loss"`

	// Average profitable trades in percentage.
	AvgProfit float64 `json:"avg_profit"`

	// Number of copiers for this trader.
	Copiers float64 `json:"copiers"`

	// Represents the net change in equity for a 12-month period.
	Last12MonthsProfitableTrades float64 `json:"last_12months_profitable_trades"`

	// Represents the net change in equity per month.
	MonthlyProfitableTrades CopytradingStatisticsRespCopytradingStatisticsMonthlyProfitableTrades `json:"monthly_profitable_trades"`

	// Trader performance probability.
	PerformanceProbability float64 `json:"performance_probability"`

	// Total number of trades for all time.
	TotalTrades int `json:"total_trades"`

	// Represents the portfolio distribution by markets.
	TradesBreakdown CopytradingStatisticsRespCopytradingStatisticsTradesBreakdown `json:"trades_breakdown"`

	// Number of profit trades in percentage.
	TradesProfitable float64 `json:"trades_profitable"`

	// Represents the net change in equity per year.
	YearlyProfitableTrades CopytradingStatisticsRespCopytradingStatisticsYearlyProfitableTrades `json:"yearly_profitable_trades,omitempty"`
}

// Represents the net change in equity per month.
type CopytradingStatisticsRespCopytradingStatisticsMonthlyProfitableTrades map[string]interface{}

// Represents the portfolio distribution by markets.
type CopytradingStatisticsRespCopytradingStatisticsTradesBreakdown map[string]interface{}

// Represents the net change in equity per year.
type CopytradingStatisticsRespCopytradingStatisticsYearlyProfitableTrades map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CopytradingStatisticsRespCopytradingStatistics) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["active_since"]; !ok || v == nil {
		return fmt.Errorf("field active_since: required")
	}
	if v, ok := raw["avg_duration"]; !ok || v == nil {
		return fmt.Errorf("field avg_duration: required")
	}
	if v, ok := raw["avg_loss"]; !ok || v == nil {
		return fmt.Errorf("field avg_loss: required")
	}
	if v, ok := raw["avg_profit"]; !ok || v == nil {
		return fmt.Errorf("field avg_profit: required")
	}
	if v, ok := raw["copiers"]; !ok || v == nil {
		return fmt.Errorf("field copiers: required")
	}
	if v, ok := raw["last_12months_profitable_trades"]; !ok || v == nil {
		return fmt.Errorf("field last_12months_profitable_trades: required")
	}
	if v, ok := raw["monthly_profitable_trades"]; !ok || v == nil {
		return fmt.Errorf("field monthly_profitable_trades: required")
	}
	if v, ok := raw["performance_probability"]; !ok || v == nil {
		return fmt.Errorf("field performance_probability: required")
	}
	if v, ok := raw["total_trades"]; !ok || v == nil {
		return fmt.Errorf("field total_trades: required")
	}
	if v, ok := raw["trades_breakdown"]; !ok || v == nil {
		return fmt.Errorf("field trades_breakdown: required")
	}
	if v, ok := raw["trades_profitable"]; !ok || v == nil {
		return fmt.Errorf("field trades_profitable: required")
	}
	type Plain CopytradingStatisticsRespCopytradingStatistics
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = CopytradingStatisticsRespCopytradingStatistics(plain)
	return nil
}

// Echo of the request made.
type CopytradingStatisticsRespEchoReq map[string]interface{}

type CopytradingStatisticsRespMsgType string

var enumValues_CopytradingStatisticsRespMsgType = []interface{}{
	"copytrading_statistics",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CopytradingStatisticsRespMsgType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CopytradingStatisticsRespMsgType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_CopytradingStatisticsRespMsgType, v)
	}
	*j = CopytradingStatisticsRespMsgType(v)
	return nil
}

// The statistics of the trader.
type CopytradingStatisticsResp struct {
	// Statistics of the trader
	CopytradingStatistics *CopytradingStatisticsRespCopytradingStatistics `json:"copytrading_statistics,omitempty"`

	// Echo of the request made.
	EchoReq CopytradingStatisticsRespEchoReq `json:"echo_req"`

	// Action name of the request made.
	MsgType CopytradingStatisticsRespMsgType `json:"msg_type"`

	// Optional field sent in request to map to response, present only when request
	// contains `req_id`.
	ReqId *int `json:"req_id,omitempty"`
}

const CopytradingStatisticsRespMsgTypeCopytradingStatistics CopytradingStatisticsRespMsgType = "copytrading_statistics"

// UnmarshalJSON implements json.Unmarshaler.
func (j *CopytradingStatisticsResp) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["echo_req"]; !ok || v == nil {
		return fmt.Errorf("field echo_req: required")
	}
	if v, ok := raw["msg_type"]; !ok || v == nil {
		return fmt.Errorf("field msg_type: required")
	}
	type Plain CopytradingStatisticsResp
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = CopytradingStatisticsResp(plain)
	return nil
}
