// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "fmt"
import "reflect"
import "encoding/json"

type GetLimitsGetLimits int

var enumValues_GetLimitsGetLimits = []interface{}{
	1,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GetLimitsGetLimits) UnmarshalJSON(b []byte) error {
	var v int
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_GetLimitsGetLimits {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_GetLimitsGetLimits, v)
	}
	*j = GetLimitsGetLimits(v)
	return nil
}

// Trading and Withdrawal Limits for a given user
type GetLimits struct {
	// Must be `1`
	GetLimits GetLimitsGetLimits `json:"get_limits"`

	// [Optional] Used to pass data through the websocket, which may be retrieved via
	// the `echo_req` output field.
	Passthrough GetLimitsPassthrough `json:"passthrough,omitempty"`

	// [Optional] Used to map request to response.
	ReqId *int `json:"req_id,omitempty"`
}

// [Optional] Used to pass data through the websocket, which may be retrieved via
// the `echo_req` output field.
type GetLimitsPassthrough map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GetLimits) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["get_limits"]; !ok || v == nil {
		return fmt.Errorf("field get_limits: required")
	}
	type Plain GetLimits
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = GetLimits(plain)
	return nil
}
