// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "encoding/json"
import "fmt"
import "reflect"

// A message with KYC Authentication Status.
type KycAuthStatusResp struct {
	// Echo of the request made.
	EchoReq KycAuthStatusRespEchoReq `json:"echo_req"`

	// Proof of Identity (POI) and Proof of Address (POA) authentication status
	// details.
	KycAuthStatus KycAuthStatusRespKycAuthStatus `json:"kyc_auth_status,omitempty"`

	// Action name of the request made.
	MsgType KycAuthStatusRespMsgType `json:"msg_type"`

	// Optional field sent in request to map to response, present only when request
	// contains `req_id`.
	ReqId *int `json:"req_id,omitempty"`
}

// Echo of the request made.
type KycAuthStatusRespEchoReq map[string]interface{}

// Proof of Identity (POI) and Proof of Address (POA) authentication status
// details.
type KycAuthStatusRespKycAuthStatus map[string]interface{}

type KycAuthStatusRespMsgType string

const KycAuthStatusRespMsgTypeKycAuthStatus KycAuthStatusRespMsgType = "kyc_auth_status"

var enumValues_KycAuthStatusRespMsgType = []interface{}{
	"kyc_auth_status",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *KycAuthStatusRespMsgType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_KycAuthStatusRespMsgType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_KycAuthStatusRespMsgType, v)
	}
	*j = KycAuthStatusRespMsgType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *KycAuthStatusResp) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["echo_req"]; raw != nil && !ok {
		return fmt.Errorf("field echo_req in KycAuthStatusResp: required")
	}
	if _, ok := raw["msg_type"]; raw != nil && !ok {
		return fmt.Errorf("field msg_type in KycAuthStatusResp: required")
	}
	type Plain KycAuthStatusResp
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = KycAuthStatusResp(plain)
	return nil
}
