// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "fmt"
import "reflect"
import "encoding/json"

// Echo of the request made.
type Mt5PasswordChangeRespEchoReq map[string]interface{}

type Mt5PasswordChangeRespMsgType string

var enumValues_Mt5PasswordChangeRespMsgType = []interface{}{
	"mt5_password_change",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Mt5PasswordChangeRespMsgType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Mt5PasswordChangeRespMsgType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Mt5PasswordChangeRespMsgType, v)
	}
	*j = Mt5PasswordChangeRespMsgType(v)
	return nil
}

// MT5 user password change receive
type Mt5PasswordChangeResp struct {
	// Echo of the request made.
	EchoReq Mt5PasswordChangeRespEchoReq `json:"echo_req"`

	// Action name of the request made.
	MsgType Mt5PasswordChangeRespMsgType `json:"msg_type"`

	// `1` on success
	Mt5PasswordChange *int `json:"mt5_password_change,omitempty"`

	// Optional field sent in request to map to response, present only when request
	// contains `req_id`.
	ReqId *int `json:"req_id,omitempty"`
}

const Mt5PasswordChangeRespMsgTypeMt5PasswordChange Mt5PasswordChangeRespMsgType = "mt5_password_change"

// UnmarshalJSON implements json.Unmarshaler.
func (j *Mt5PasswordChangeResp) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["echo_req"]; !ok || v == nil {
		return fmt.Errorf("field echo_req: required")
	}
	if v, ok := raw["msg_type"]; !ok || v == nil {
		return fmt.Errorf("field msg_type: required")
	}
	type Plain Mt5PasswordChangeResp
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = Mt5PasswordChangeResp(plain)
	return nil
}
