// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "encoding/json"
import "fmt"
import "reflect"

// Response for checking if name and date of birth match an existing account.
type NewAccountWalletCheckDuplicateNameAndDobResp struct {
	// Echo of the request made.
	EchoReq NewAccountWalletCheckDuplicateNameAndDobRespEchoReq `json:"echo_req"`

	// Action name of the request made.
	MsgType NewAccountWalletCheckDuplicateNameAndDobRespMsgType `json:"msg_type"`

	// The result of checking for duplicate name and date of birth
	NewAccountWalletCheckDuplicateNameAndDob *NewAccountWalletCheckDuplicateNameAndDobRespNewAccountWalletCheckDuplicateNameAndDob `json:"new_account_wallet_check_duplicate_name_and_dob,omitempty"`

	// Optional field sent in request to map to response, present only when request
	// contains `req_id`.
	ReqId *int `json:"req_id,omitempty"`
}

// Echo of the request made.
type NewAccountWalletCheckDuplicateNameAndDobRespEchoReq map[string]interface{}

type NewAccountWalletCheckDuplicateNameAndDobRespMsgType string

const NewAccountWalletCheckDuplicateNameAndDobRespMsgTypeNewAccountWalletCheckDuplicateNameAndDob NewAccountWalletCheckDuplicateNameAndDobRespMsgType = "new_account_wallet_check_duplicate_name_and_dob"

var enumValues_NewAccountWalletCheckDuplicateNameAndDobRespMsgType = []interface{}{
	"new_account_wallet_check_duplicate_name_and_dob",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NewAccountWalletCheckDuplicateNameAndDobRespMsgType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NewAccountWalletCheckDuplicateNameAndDobRespMsgType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NewAccountWalletCheckDuplicateNameAndDobRespMsgType, v)
	}
	*j = NewAccountWalletCheckDuplicateNameAndDobRespMsgType(v)
	return nil
}

// The result of checking for duplicate name and date of birth
type NewAccountWalletCheckDuplicateNameAndDobRespNewAccountWalletCheckDuplicateNameAndDob struct {
	// 1 if a matching account was found, 0 if not
	HasDuplicate NewAccountWalletCheckDuplicateNameAndDobRespNewAccountWalletCheckDuplicateNameAndDobHasDuplicate `json:"has_duplicate"`
}

type NewAccountWalletCheckDuplicateNameAndDobRespNewAccountWalletCheckDuplicateNameAndDobHasDuplicate int

var enumValues_NewAccountWalletCheckDuplicateNameAndDobRespNewAccountWalletCheckDuplicateNameAndDobHasDuplicate = []interface{}{
	0,
	1,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NewAccountWalletCheckDuplicateNameAndDobRespNewAccountWalletCheckDuplicateNameAndDobHasDuplicate) UnmarshalJSON(b []byte) error {
	var v int
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NewAccountWalletCheckDuplicateNameAndDobRespNewAccountWalletCheckDuplicateNameAndDobHasDuplicate {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NewAccountWalletCheckDuplicateNameAndDobRespNewAccountWalletCheckDuplicateNameAndDobHasDuplicate, v)
	}
	*j = NewAccountWalletCheckDuplicateNameAndDobRespNewAccountWalletCheckDuplicateNameAndDobHasDuplicate(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NewAccountWalletCheckDuplicateNameAndDobRespNewAccountWalletCheckDuplicateNameAndDob) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["has_duplicate"]; raw != nil && !ok {
		return fmt.Errorf("field has_duplicate in NewAccountWalletCheckDuplicateNameAndDobRespNewAccountWalletCheckDuplicateNameAndDob: required")
	}
	type Plain NewAccountWalletCheckDuplicateNameAndDobRespNewAccountWalletCheckDuplicateNameAndDob
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = NewAccountWalletCheckDuplicateNameAndDobRespNewAccountWalletCheckDuplicateNameAndDob(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NewAccountWalletCheckDuplicateNameAndDobResp) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["echo_req"]; raw != nil && !ok {
		return fmt.Errorf("field echo_req in NewAccountWalletCheckDuplicateNameAndDobResp: required")
	}
	if _, ok := raw["msg_type"]; raw != nil && !ok {
		return fmt.Errorf("field msg_type in NewAccountWalletCheckDuplicateNameAndDobResp: required")
	}
	type Plain NewAccountWalletCheckDuplicateNameAndDobResp
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = NewAccountWalletCheckDuplicateNameAndDobResp(plain)
	return nil
}
