// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "encoding/json"
import "fmt"
import "reflect"

// Create real account Receive
type NewAccountRealResp struct {
	// Echo of the request made.
	EchoReq NewAccountRealRespEchoReq `json:"echo_req"`

	// Action name of the request made.
	MsgType NewAccountRealRespMsgType `json:"msg_type"`

	// New real money account details
	NewAccountReal *NewAccountRealRespNewAccountReal `json:"new_account_real,omitempty"`

	// Optional field sent in request to map to response, present only when request
	// contains `req_id`.
	ReqId *int `json:"req_id,omitempty"`
}

// Echo of the request made.
type NewAccountRealRespEchoReq map[string]interface{}

type NewAccountRealRespMsgType string

const NewAccountRealRespMsgTypeNewAccountReal NewAccountRealRespMsgType = "new_account_real"

var enumValues_NewAccountRealRespMsgType = []interface{}{
	"new_account_real",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NewAccountRealRespMsgType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NewAccountRealRespMsgType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NewAccountRealRespMsgType, v)
	}
	*j = NewAccountRealRespMsgType(v)
	return nil
}

// New real money account details
type NewAccountRealRespNewAccountReal struct {
	// Client ID of new real money account
	ClientId string `json:"client_id"`

	// Currency of an account
	Currency *string `json:"currency,omitempty"`

	// Landing company full name
	LandingCompany string `json:"landing_company"`

	// Landing company shortcode
	LandingCompanyShort *string `json:"landing_company_short,omitempty"`

	// Landing company shortcode
	LandingCompanyShortcode *string `json:"landing_company_shortcode,omitempty"`

	// OAuth token for client's login session
	OauthToken string `json:"oauth_token"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NewAccountRealRespNewAccountReal) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["client_id"]; raw != nil && !ok {
		return fmt.Errorf("field client_id in NewAccountRealRespNewAccountReal: required")
	}
	if _, ok := raw["landing_company"]; raw != nil && !ok {
		return fmt.Errorf("field landing_company in NewAccountRealRespNewAccountReal: required")
	}
	if _, ok := raw["oauth_token"]; raw != nil && !ok {
		return fmt.Errorf("field oauth_token in NewAccountRealRespNewAccountReal: required")
	}
	type Plain NewAccountRealRespNewAccountReal
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = NewAccountRealRespNewAccountReal(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NewAccountRealResp) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["echo_req"]; raw != nil && !ok {
		return fmt.Errorf("field echo_req in NewAccountRealResp: required")
	}
	if _, ok := raw["msg_type"]; raw != nil && !ok {
		return fmt.Errorf("field msg_type in NewAccountRealResp: required")
	}
	type Plain NewAccountRealResp
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = NewAccountRealResp(plain)
	return nil
}
