// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "encoding/json"
import "fmt"
import "reflect"

// Echo of the request made.
type P2PAdvertiserPaymentMethodsRespEchoReq map[string]interface{}

type P2PAdvertiserPaymentMethodsRespMsgType string

var enumValues_P2PAdvertiserPaymentMethodsRespMsgType = []interface{}{
	"p2p_advertiser_payment_methods",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *P2PAdvertiserPaymentMethodsRespMsgType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_P2PAdvertiserPaymentMethodsRespMsgType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_P2PAdvertiserPaymentMethodsRespMsgType, v)
	}
	*j = P2PAdvertiserPaymentMethodsRespMsgType(v)
	return nil
}

// List P2P advertiser payment methods.
type P2PAdvertiserPaymentMethodsResp struct {
	// Echo of the request made.
	EchoReq P2PAdvertiserPaymentMethodsRespEchoReq `json:"echo_req"`

	// Action name of the request made.
	MsgType P2PAdvertiserPaymentMethodsRespMsgType `json:"msg_type"`

	// List of current methods.
	P2PAdvertiserPaymentMethods P2PAdvertiserPaymentMethodsRespP2PAdvertiserPaymentMethods `json:"p2p_advertiser_payment_methods,omitempty"`

	// Optional field sent in request to map to response, present only when request
	// contains `req_id`.
	ReqId *int `json:"req_id,omitempty"`
}

const P2PAdvertiserPaymentMethodsRespMsgTypeP2PAdvertiserPaymentMethods P2PAdvertiserPaymentMethodsRespMsgType = "p2p_advertiser_payment_methods"

// List of current methods.
type P2PAdvertiserPaymentMethodsRespP2PAdvertiserPaymentMethods map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *P2PAdvertiserPaymentMethodsResp) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["echo_req"]; !ok || v == nil {
		return fmt.Errorf("field echo_req in P2PAdvertiserPaymentMethodsResp: required")
	}
	if v, ok := raw["msg_type"]; !ok || v == nil {
		return fmt.Errorf("field msg_type in P2PAdvertiserPaymentMethodsResp: required")
	}
	type Plain P2PAdvertiserPaymentMethodsResp
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = P2PAdvertiserPaymentMethodsResp(plain)
	return nil
}
