// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "encoding/json"
import "fmt"
import "reflect"

// Confirm a P2P order.
type P2POrderConfirm struct {
	// [Optional] If set to `1`, only validation is performed.
	DryRun P2POrderConfirmDryRun `json:"dry_run,omitempty"`

	// The unique identifier for this order.
	Id string `json:"id"`

	// [Optional] The login id of the user. If left unspecified, it defaults to the
	// initial authorized token's login id.
	Loginid *string `json:"loginid,omitempty"`

	// Must be 1
	P2POrderConfirm P2POrderConfirmP2POrderConfirm `json:"p2p_order_confirm"`

	// [Optional] Used to pass data through the websocket, which may be retrieved via
	// the `echo_req` output field.
	Passthrough P2POrderConfirmPassthrough `json:"passthrough,omitempty"`

	// [Optional] Used to map request to response.
	ReqId *int `json:"req_id,omitempty"`

	// [Optional] Verification code received from email.
	VerificationCode *string `json:"verification_code,omitempty"`
}

type P2POrderConfirmDryRun int

var enumValues_P2POrderConfirmDryRun = []interface{}{
	0,
	1,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *P2POrderConfirmDryRun) UnmarshalJSON(b []byte) error {
	var v int
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_P2POrderConfirmDryRun {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_P2POrderConfirmDryRun, v)
	}
	*j = P2POrderConfirmDryRun(v)
	return nil
}

type P2POrderConfirmP2POrderConfirm int

var enumValues_P2POrderConfirmP2POrderConfirm = []interface{}{
	1,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *P2POrderConfirmP2POrderConfirm) UnmarshalJSON(b []byte) error {
	var v int
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_P2POrderConfirmP2POrderConfirm {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_P2POrderConfirmP2POrderConfirm, v)
	}
	*j = P2POrderConfirmP2POrderConfirm(v)
	return nil
}

// [Optional] Used to pass data through the websocket, which may be retrieved via
// the `echo_req` output field.
type P2POrderConfirmPassthrough map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *P2POrderConfirm) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in P2POrderConfirm: required")
	}
	if _, ok := raw["p2p_order_confirm"]; raw != nil && !ok {
		return fmt.Errorf("field p2p_order_confirm in P2POrderConfirm: required")
	}
	type Plain P2POrderConfirm
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if v, ok := raw["dry_run"]; !ok || v == nil {
		plain.DryRun = 0.0
	}
	*j = P2POrderConfirm(plain)
	return nil
}
