// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "encoding/json"
import "fmt"
import "reflect"

// Manage or list P2P advertiser payment methods.
type P2PAdvertiserPaymentMethods struct {
	// Contains new payment method entries.
	Create []P2PAdvertiserPaymentMethodsCreateElem `json:"create,omitempty"`

	// Contains payment methods to delete.
	Delete []float64 `json:"delete,omitempty"`

	// [Optional] The login id of the user. If left unspecified, it defaults to the
	// initial authorized token's login id.
	Loginid *string `json:"loginid,omitempty"`

	// Must be 1
	P2PAdvertiserPaymentMethods P2PAdvertiserPaymentMethodsP2PAdvertiserPaymentMethods `json:"p2p_advertiser_payment_methods"`

	// [Optional] Used to pass data through the websocket, which may be retrieved via
	// the `echo_req` output field.
	Passthrough P2PAdvertiserPaymentMethodsPassthrough `json:"passthrough,omitempty"`

	// [Optional] Used to map request to response.
	ReqId *int `json:"req_id,omitempty"`

	// Contains payment methods to update.
	Update P2PAdvertiserPaymentMethodsUpdate `json:"update,omitempty"`
}

type P2PAdvertiserPaymentMethodsCreateElem struct {
	// Payment method identifer.
	Method string `json:"method"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *P2PAdvertiserPaymentMethodsCreateElem) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["method"]; raw != nil && !ok {
		return fmt.Errorf("field method in P2PAdvertiserPaymentMethodsCreateElem: required")
	}
	type Plain P2PAdvertiserPaymentMethodsCreateElem
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = P2PAdvertiserPaymentMethodsCreateElem(plain)
	return nil
}

type P2PAdvertiserPaymentMethodsP2PAdvertiserPaymentMethods int

var enumValues_P2PAdvertiserPaymentMethodsP2PAdvertiserPaymentMethods = []interface{}{
	1,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *P2PAdvertiserPaymentMethodsP2PAdvertiserPaymentMethods) UnmarshalJSON(b []byte) error {
	var v int
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_P2PAdvertiserPaymentMethodsP2PAdvertiserPaymentMethods {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_P2PAdvertiserPaymentMethodsP2PAdvertiserPaymentMethods, v)
	}
	*j = P2PAdvertiserPaymentMethodsP2PAdvertiserPaymentMethods(v)
	return nil
}

// [Optional] Used to pass data through the websocket, which may be retrieved via
// the `echo_req` output field.
type P2PAdvertiserPaymentMethodsPassthrough map[string]interface{}

// Contains payment methods to update.
type P2PAdvertiserPaymentMethodsUpdate map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *P2PAdvertiserPaymentMethods) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["p2p_advertiser_payment_methods"]; raw != nil && !ok {
		return fmt.Errorf("field p2p_advertiser_payment_methods in P2PAdvertiserPaymentMethods: required")
	}
	type Plain P2PAdvertiserPaymentMethods
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if plain.Create != nil && len(plain.Create) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "create", 1)
	}
	if len(plain.Create) > 100 {
		return fmt.Errorf("field %s length: must be <= %d", "create", 100)
	}
	if plain.Delete != nil && len(plain.Delete) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "delete", 1)
	}
	if len(plain.Delete) > 100 {
		return fmt.Errorf("field %s length: must be <= %d", "delete", 100)
	}
	*j = P2PAdvertiserPaymentMethods(plain)
	return nil
}
