// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "encoding/json"
import "fmt"
import "reflect"

// [Optional] Used to pass data through the websocket, which may be retrieved via
// the `echo_req` output field. Maximum size is 3500 bytes.
type PaymentMethodsPassthrough map[string]interface{}

type PaymentMethodsPaymentMethods int

var enumValues_PaymentMethodsPaymentMethods = []interface{}{
	1,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PaymentMethodsPaymentMethods) UnmarshalJSON(b []byte) error {
	var v int
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_PaymentMethodsPaymentMethods {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_PaymentMethodsPaymentMethods, v)
	}
	*j = PaymentMethodsPaymentMethods(v)
	return nil
}

// Will return a list payment methods available for the given country. If the
// request is authenticated the client's residence country will be used.
type PaymentMethods struct {
	// [Optional] 2-letter country code (ISO standard).
	Country *string `json:"country,omitempty"`

	// [Optional] Used to pass data through the websocket, which may be retrieved via
	// the `echo_req` output field. Maximum size is 3500 bytes.
	Passthrough PaymentMethodsPassthrough `json:"passthrough,omitempty"`

	// Must be `1`
	PaymentMethods PaymentMethodsPaymentMethods `json:"payment_methods"`

	// [Optional] Used to map request to response.
	ReqId *int `json:"req_id,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PaymentMethods) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["payment_methods"]; !ok || v == nil {
		return fmt.Errorf("field payment_methods in PaymentMethods: required")
	}
	type Plain PaymentMethods
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = PaymentMethods(plain)
	return nil
}
