// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "encoding/json"
import "fmt"
import "reflect"

// Echo of the request made.
type SellContractForMultipleAccountsRespEchoReq map[string]interface{}

type SellContractForMultipleAccountsRespMsgType string

var enumValues_SellContractForMultipleAccountsRespMsgType = []interface{}{
	"sell_contract_for_multiple_accounts",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SellContractForMultipleAccountsRespMsgType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SellContractForMultipleAccountsRespMsgType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SellContractForMultipleAccountsRespMsgType, v)
	}
	*j = SellContractForMultipleAccountsRespMsgType(v)
	return nil
}

// Confirmation of the sale status for the selected contracts and accounts.
type SellContractForMultipleAccountsResp struct {
	// Echo of the request made.
	EchoReq SellContractForMultipleAccountsRespEchoReq `json:"echo_req"`

	// Action name of the request made.
	MsgType SellContractForMultipleAccountsRespMsgType `json:"msg_type"`

	// Optional field sent in request to map to response, present only when request
	// contains `req_id`.
	ReqId *int `json:"req_id,omitempty"`

	// Status information for each affected account.
	SellContractForMultipleAccounts *SellContractForMultipleAccountsRespSellContractForMultipleAccounts `json:"sell_contract_for_multiple_accounts,omitempty"`
}

const SellContractForMultipleAccountsRespMsgTypeSellContractForMultipleAccounts SellContractForMultipleAccountsRespMsgType = "sell_contract_for_multiple_accounts"

// Status information for each affected account.
type SellContractForMultipleAccountsRespSellContractForMultipleAccounts struct {
	// The result of sell for multiple accounts request.
	Result []interface{} `json:"result,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SellContractForMultipleAccountsResp) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["echo_req"]; !ok || v == nil {
		return fmt.Errorf("field echo_req in SellContractForMultipleAccountsResp: required")
	}
	if v, ok := raw["msg_type"]; !ok || v == nil {
		return fmt.Errorf("field msg_type in SellContractForMultipleAccountsResp: required")
	}
	type Plain SellContractForMultipleAccountsResp
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = SellContractForMultipleAccountsResp(plain)
	return nil
}
