// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "encoding/json"
import "fmt"
import "reflect"

// Echo of the request made.
type TradingPlatformStatusRespEchoReq map[string]interface{}

type TradingPlatformStatusRespMsgType string

var enumValues_TradingPlatformStatusRespMsgType = []interface{}{
	"trading_platform_status",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TradingPlatformStatusRespMsgType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TradingPlatformStatusRespMsgType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TradingPlatformStatusRespMsgType, v)
	}
	*j = TradingPlatformStatusRespMsgType(v)
	return nil
}

// Provides current suspension status of trading platforms
type TradingPlatformStatusResp struct {
	// Echo of the request made.
	EchoReq TradingPlatformStatusRespEchoReq `json:"echo_req"`

	// Action name of the request made.
	MsgType TradingPlatformStatusRespMsgType `json:"msg_type"`

	// Optional field sent in request to map to response, present only when request
	// contains `req_id`.
	ReqId *int `json:"req_id,omitempty"`

	// Availability status of the trading platforms
	TradingPlatformStatus []interface{} `json:"trading_platform_status"`
}

const TradingPlatformStatusRespMsgTypeTradingPlatformStatus TradingPlatformStatusRespMsgType = "trading_platform_status"

// UnmarshalJSON implements json.Unmarshaler.
func (j *TradingPlatformStatusResp) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["echo_req"]; !ok || v == nil {
		return fmt.Errorf("field echo_req in TradingPlatformStatusResp: required")
	}
	if v, ok := raw["msg_type"]; !ok || v == nil {
		return fmt.Errorf("field msg_type in TradingPlatformStatusResp: required")
	}
	if v, ok := raw["trading_platform_status"]; !ok || v == nil {
		return fmt.Errorf("field trading_platform_status in TradingPlatformStatusResp: required")
	}
	type Plain TradingPlatformStatusResp
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = TradingPlatformStatusResp(plain)
	return nil
}
