// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "encoding/json"
import "fmt"
import "reflect"

// [Optional] Used to pass data through the websocket, which may be retrieved via
// the `echo_req` output field.
type TradingPlatformStatusPassthrough map[string]interface{}

type TradingPlatformStatusTradingPlatformStatus int

var enumValues_TradingPlatformStatusTradingPlatformStatus = []interface{}{
	1,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TradingPlatformStatusTradingPlatformStatus) UnmarshalJSON(b []byte) error {
	var v int
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TradingPlatformStatusTradingPlatformStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TradingPlatformStatusTradingPlatformStatus, v)
	}
	*j = TradingPlatformStatusTradingPlatformStatus(v)
	return nil
}

// Request trading platform status
type TradingPlatformStatus struct {
	// [Optional] Used to pass data through the websocket, which may be retrieved via
	// the `echo_req` output field.
	Passthrough TradingPlatformStatusPassthrough `json:"passthrough,omitempty"`

	// [Optional] Used to map request to response.
	ReqId *int `json:"req_id,omitempty"`

	// Must be `1`
	TradingPlatformStatus TradingPlatformStatusTradingPlatformStatus `json:"trading_platform_status"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TradingPlatformStatus) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["trading_platform_status"]; !ok || v == nil {
		return fmt.Errorf("field trading_platform_status in TradingPlatformStatus: required")
	}
	type Plain TradingPlatformStatus
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = TradingPlatformStatus(plain)
	return nil
}
