name: Deriv API

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.21.x", "1.22.x", "1.23.x"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version
      - name: Code Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.1
      - name: Build
        run: go build -v .
      - name: Test
        run: go test -coverprofile=coverage.out -covermode=atomic -v --race .
      - name: Prepare coverage reports
        run: |
          cat coverage.out | grep -v "/schema.go" | grep -v "/calls.go" | grep -v "/custom_subscription_calls.go" | grep -v "subscription_calls.go" > coverage.final.out
          mv coverage.final.out coverage.out
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
