name: Deriv API 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.19.x', '1.20.x', '1.21.x' ]

    steps:
      - uses: actions/checkout@v3   
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Build
        run: go build -v .
      - name: Test
        run: go test -coverprofile=coverage.out -covermode=atomic -v --race .
      - name: Prepare coverage reports
        run: |
          cat coverage.out | grep -v "/schema.go" | grep -v "/calls.go" | grep -v "subscription_calls.go" > coverage.final.out
          mv coverage.final.out coverage.out
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3