name: Schema Updater 
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Display Go version
        run: go version
      - name: Install schema generator
        run: go install github.com/atombender/go-jsonschema/cmd/gojsonschema@v0.8.0
      - name: generate schema
        run: make all

      - name: Test
        run: go test -coverprofile=coverage.out -covermode=atomic -v .

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Updates API schema'
          add: '*.go'