permissions:
  contents: write
name: Schema Updater
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Display Go version
        run: go version
      - name: Install schema generator
        run: go install github.com/atombender/go-jsonschema@v0.16.0
      - name: generate schema
        run: make generate_all

      - name: Test
        run: go test -coverprofile=coverage.out -covermode=atomic -v --race .

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: user_info
          message: "Updates API schema"
          add: "*.go"
